const books = [
    { title: 'The Great Gatsby', author: 'F. Scott Fitzgerald', coverImage: 'https://placehold.it/80x100' },
    { title: '1984', author: 'George Orwell', coverImage: 'https://placehold.it/80x100' },
    { title: 'To Kill a Mockingbird', author: 'Harper Lee', coverImage: 'https://placehold.it/80x100' },
    { title: 'Moby-Dick', author: 'Herman Melville', coverImage: 'https://placehold.it/80x100' },
    { title: 'Pride and Prejudice', author: 'Jane Austen', coverImage: 'https://placehold.it/80x100' },
    { title: 'War and Peace', author: 'Leo Tolstoy', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Catcher in the Rye', author: 'J.D. Salinger', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Hobbit', author: 'J.R.R. Tolkien', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Lord of the Rings', author: 'J.R.R. Tolkien', coverImage: 'https://placehold.it/80x100' },
    { title: 'Fahrenheit 451', author: 'Ray Bradbury', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Road', author: 'Cormac McCarthy', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Book Thief', author: 'Markus Zusak', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Odyssey', author: 'Homer', coverImage: 'https://placehold.it/80x100' },
    { title: 'Crime and Punishment', author: 'Fyodor Dostoevsky', coverImage: 'https://placehold.it/80x100' },
    { title: 'Brave New World', author: 'Aldous Huxley', coverImage: 'https://placehold.it/80x100' },
    { title: 'Frankenstein', author: 'Mary Shelley', coverImage: 'https://placehold.it/80x100' },
    { title: 'Dracula', author: 'Bram Stoker', coverImage: 'https://placehold.it/80x100' },
    { title: 'Catch-22', author: 'Joseph Heller', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Grapes of Wrath', author: 'John Steinbeck', coverImage: 'https://placehold.it/80x100' },
    { title: 'Slaughterhouse-Five', author: 'Kurt Vonnegut', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Picture of Dorian Gray', author: 'Oscar Wilde', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Chronicles of Narnia', author: 'C.S. Lewis', coverImage: 'https://placehold.it/80x100' },
    { title: 'A Tale of Two Cities', author: 'Charles Dickens', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Count of Monte Cristo', author: 'Alexandre Dumas', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Divine Comedy', author: 'Dante Alighieri', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Brothers Karamazov', author: 'Fyodor Dostoevsky', coverImage: 'https://placehold.it/80x100' },
    { title: 'Anna Karenina', author: 'Leo Tolstoy', coverImage: 'https://placehold.it/80x100' },
    { title: 'Les Misérables', author: 'Victor Hugo', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Stranger', author: 'Albert Camus', coverImage: 'https://placehold.it/80x100' },
    { title: 'A Clockwork Orange', author: 'Anthony Burgess', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Bell Jar', author: 'Sylvia Plath', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Sun Also Rises', author: 'Ernest Hemingway', coverImage: 'https://placehold.it/80x100' },
    { title: 'Siddhartha', author: 'Hermann Hesse', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Alchemist', author: 'Paulo Coelho', coverImage: 'https://placehold.it/80x100' },
    { title: 'One Hundred Years of Solitude', author: 'Gabriel García Márquez', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Sound and the Fury', author: 'William Faulkner', coverImage: 'https://placehold.it/80x100' },
    { title: 'Wuthering Heights', author: 'Emily Brontë', coverImage: 'https://placehold.it/80x100' },
    { title: 'Jane Eyre', author: 'Charlotte Brontë', coverImage: 'https://placehold.it/80x100' },
    { title: 'Rebecca', author: 'Daphne du Maurier', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Secret Garden', author: 'Frances Hodgson Burnett', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Girl on the Train', author: 'Paula Hawkins', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Hunger Games', author: 'Suzanne Collins', coverImage: 'https://placehold.it/80x100' },
    { title: 'Divergent', author: 'Veronica Roth', coverImage: 'https://placehold.it/80x100' },
    { title: 'Twilight', author: 'Stephenie Meyer', coverImage: 'https://placehold.it/80x100' },
    { title: 'Harry Potter and the Sorcerer\'s Stone', author: 'J.K. Rowling', coverImage: 'https://placehold.it/80x100' },
    { title: 'A Game of Thrones', author: 'George R.R. Martin', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Shining', author: 'Stephen King', coverImage: 'https://placehold.it/80x100' },
    { title: 'It', author: 'Stephen King', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Outsiders', author: 'S.E. Hinton', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Fault in Our Stars', author: 'John Green', coverImage: 'https://placehold.it/80x100' },
    { title: 'Looking for Alaska', author: 'John Green', coverImage: 'https://placehold.it/80x100' },
    { title: 'Eleanor & Park', author: 'Rainbow Rowell', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Perks of Being a Wallflower', author: 'Stephen Chbosky', coverImage: 'https://placehold.it/80x100' },
    { title: 'All the Light We Cannot See', author: 'Anthony Doerr', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Night Circus', author: 'Erin Morgenstern', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Goldfinch', author: 'Donna Tartt', coverImage: 'https://placehold.it/80x100' },
    { title: 'Where the Crawdads Sing', author: 'Delia Owens', coverImage: 'https://placehold.it/80x100' },
    { title: 'Circe', author: 'Madeline Miller', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Silent Patient', author: 'Alex Michaelides', coverImage: 'https://placehold.it/80x100' },
    { title: 'Big Little Lies', author: 'Liane Moriarty', coverImage: 'https://placehold.it/80x100' },
    { title: 'Sharp Objects', author: 'Gillian Flynn', coverImage: 'https://placehold.it/80x100' },
    { title: 'Gone Girl', author: 'Gillian Flynn', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Couple Next Door', author: 'Shari Lapena', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Woman in the Window', author: 'A.J. Finn', coverImage: 'https://placehold.it/80x100' },
    { title: 'Behind Closed Doors', author: 'B.A. Paris', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Wife Between Us', author: 'Greer Hendricks & Sarah Pekkanen', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Turn of the Key', author: 'Ruth Ware', coverImage: 'https://placehold.it/80x100' },
    { title: 'Before I Go to Sleep', author: 'S.J. Watson', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Girl with the Dragon Tattoo', author: 'Stieg Larsson', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Girl in the Spider\'s Web', author: 'David Lagercrantz', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Hound of the Baskervilles', author: 'Arthur Conan Doyle', coverImage: 'https://placehold.it/80x100' },
    { title: 'Sherlock Holmes: The Complete Collection', author: 'Arthur Conan Doyle', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Complete Works of William Shakespeare', author: 'William Shakespeare', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Call of the Wild', author: 'Jack London', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Jungle Book', author: 'Rudyard Kipling', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Adventures of Huckleberry Finn', author: 'Mark Twain', coverImage: 'https://placehold.it/80x100' },
    { title: 'Treasure Island', author: 'Robert Louis Stevenson', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Scarlet Pimpernel', author: 'Baroness Orczy', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Three Musketeers', author: 'Alexandre Dumas', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Call of Cthulhu', author: 'H.P. Lovecraft', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Shadow over Innsmouth', author: 'H.P. Lovecraft', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Colour Out of Space', author: 'H.P. Lovecraft', coverImage: 'https://placehold.it/80x100' },
    { title: 'The Dunwich Horror', author: 'H.P. Lovecraft', coverImage: 'https://placehold.it/80x100' }
];


export default books;